SeparationMode	separation_mode
Sex	sex
admissionDiagnosis	admission_diagnosis
admissionProcedure	admission_procedure
admissionSource	admission_source
admissionType	admission_type
careType	care_type
diagnosisDesc	diagnosis_desc
procedureDesc	procedure_desc

