

DROP TABLE IF EXISTS block;
CREATE TABLE block(
  block varchar(4),
  block_desc varchar(300) default NULL,
  PRIMARY KEY  (block)
) ;

INSERT INTO block(block, block_desc) VALUES
(1,'Examination of skull, meninges or brain'),
(2,'Cranial tap or puncture'),
(3,'Insertion of intracranial cerebrospinal fluid devices'),
(4,'Removal of intracranial cerebrospinal fluid devices'),
(5,'Irrigation, insertion or removal of intracranial cerebrospinal fluid shunt'),
(6,'Other application, insertion or removal procedures on skull, meninges or brain'),
(7,'Incisional exploration of meninges or brain'),
(8,'Intracranial drainage'),
(9,'Intracranial decompression'),
(10,'Postoperative reopening of craniotomy or craniectomy site'),
(11,'Destruction of intracranial aneurysm or other vascular lesion'),
(12,'Biopsy of brain or meninges'),
(13,'Excision of lesion of skull'),
(14,'Removal of intracranial haematoma or abscess'),
(15,'Removal of intracranial lesion'),
(16,'Other intracranial excision'),
(17,'Skull base surgery for lesion'),
(18,'BLOCK NOT USED IN ACHI 9th EDITION'),
(19,'Ventriculostomy'),
(20,'Repair of dura of brain'),
(21,'Extracranial to intracranial bypass'),
(22,'Other repair of meninges or brain'),
(23,'Cranioplasty'),
(24,'Revision of intracranial cerebrospinal fluid shunt'),
(25,'Procedures for skull fracture'),
(27,'Functional intracranial stereotactic procedure'),
(28,'Other procedures on skull, meninges or brain'),
(29,'Examination of spinal canal and spinal cord structures'),
(30,'Lumbar puncture'),
(31,'Application, insertion or removal procedures on vertebra or intervertebral disc'),
(32,'Epidural injection'),
(33,'Epidural infusion'),
(34,'Caudal injection'),
(35,'Caudal infusion'),
(36,'Spinal injection'),
(37,'Spinal infusion'),
(38,'Spinal blood patch'),
(39,'Insertion of spinal catheter, infusion device or pump'),
(40,'Removal of spinal catheter, infusion device or pump'),
(41,'Insertion and removal of spinal cerebrospinal fluid drain'),
(42,'Insertion and removal of spinal cerebrospinal fluid shunt'),
(43,'Insertion, replacement or removal of epidural electrodes'),
(44,'BLOCK NOT USED IN ACHI 9th EDITION'),
(45,'Cordotomy or myelotomy'),
(46,'Decompression of cervical spinal cord'),
(47,'Decompression of thoracic and thoracolumbar spinal cord'),
(48,'Decompression of lumbar spinal canal'),
(49,'Other incision procedures on spinal canal or spinal cord structures'),
(50,'Biopsy of spinal cord or spinal meninges'),
(51,'Discectomy for recurrent disc lesion'),
(52,'Other discectomy'),
(53,'Removal of spinal lesion'),
(54,'Other excision procedures on spinal canal or spinal cord structures'),
(55,'Repair of spinal canal or spinal cord structures'),
(56,'Revision procedures on spinal canal or spinal cord structures'),
(58,'Functional spinal stereotactic procedure'),
(59,'Other procedures on spinal canal or spinal cord structures'),
(60,'Administration of anaesthetic agent around cranial nerve'),
(61,'Administration of neurolytic agent into cranial nerve'),
(62,'Administration of agent into posterior primary rami of spinal nerve'),
(63,'Administration of anaesthetic agent around other peripheral nerve'),
(64,'Administration of neurolytic agent into other peripheral nerve'),
(65,'Administration of therapeutic agent around sympathetic nervous system'),
(66,'Administration of neurolytic agent into sympathetic nervous system'),
(67,'Insertion, replacement or removal of peripheral nerve electrodes'),
(68,'Exploration of brachial plexus'),
(69,'Incision of optic nerve meninges'),
(70,'Trigeminal gangliotomy'),
(71,'Percutaneous neurotomy of primary posterior rami of spinal nerve'),
(72,'Percutaneous neurotomy of other peripheral nerve'),
(73,'Division of intracranial nerve'),
(74,'Division of peripheral nerve'),
(75,'Decompression of intracranial nerve'),
(76,'Release of carpal and tarsal tunnel'),
(77,'Other neurolysis of peripheral nerve and nerve trunk'),
(78,'Destruction of nerve'),
(79,'Biopsy of nerve'),
(80,'Removal of lesion of nerve'),
(81,'Surgical sympathectomy'),
(82,'Other neurectomy'),
(83,'Repair of nerve or nerve trunk'),
(84,'Secondary repair of nerve or nerve trunk'),
(85,'Reoperation for previous sympathectomy'),
(86,'Other procedures on nerves'),
(110,'Application, insertion or removal procedures on thyroid or parathyroid gland'),
(111,'Incision procedures on thyroid'),
(112,'Biopsy of parathyroid or thyroid gland'),
(113,'Parathyroidectomy'),
(114,'Thyroidectomy'),
(115,'BLOCK NOT USED IN ACHI 9th EDITION'),
(116,'Other excision procedures on thyroid or parathyroid gland'),
(117,'Other procedures on thyroid or parathyroid gland'),
(118,'Biopsy of adrenal gland'),
(119,'Adrenalectomy'),
(120,'BLOCK NOT USED IN ACHI 9th EDITION'),
(121,'Other procedures on adrenal gland'),
(122,'Excision procedures on pineal gland'),
(123,'Other procedures on pineal gland'),
(124,'Biopsy of pituitary gland'),
(125,'Other excision procedures on pituitary gland'),
(126,'Other procedures on pituitary gland'),
(127,'Biopsy of thymus'),
(128,'Removal of thymus'),
(129,'Other procedures on thymus'),
(160,'Examination procedures on eyeball'),
(161,'Excision procedures on eyeball'),
(162,'Repair of perforating wound of eyeball'),
(163,'Other repair procedures on eyeball'),
(164,'Secondary procedures after removal of eyeball'),
(165,'Other procedures on eyeball'),
(166,'Application, insertion or removal procedures on cornea'),
(167,'Incision procedures on cornea'),
(168,'Destruction procedures on cornea'),
(169,'Biopsy of cornea'),
(170,'Keratectomy'),
(171,'Excision of lesion of limbus'),
(172,'Other excision procedures on cornea'),
(173,'Keratoplasty'),
(174,'Other repair procedures on cornea'),
(175,'Reoperation procedures on cornea'),
(176,'Other procedures on cornea'),
(177,'Application, insertion or removal procedures on sclera'),
(178,'Incision procedures on sclera'),
(179,'Destruction procedures on sclera'),
(180,'Biopsy of sclera'),
(181,'Other excision procedures on sclera'),
(182,'Repair procedures on sclera'),
(183,'Revision procedures on sclera'),
(184,'Other procedures on sclera'),
(185,'Application, insertion or removal procedures on iris, ciliary body or anterior chamber'),
(186,'Division of synechiae'),
(187,'Other incision procedures on iris, ciliary body or anterior chamber'),
(188,'Destruction procedures on iris, ciliary body or anterior chamber'),
(189,'Excision procedures on iris, ciliary body or anterior chamber'),
(190,'Repair procedures on iris, ciliary body or anterior chamber'),
(191,'Procedures for glaucoma'),
(192,'Other procedures on iris, ciliary body or anterior chamber'),
(193,'Insertion of intraocular lens prosthesis'),
(194,'Replacement or removal of artificial lens'),
(195,'Intracapsular crystalline lens extraction'),
(196,'Extracapsular crystalline lens extraction by aspiration alone'),
(197,'Extracapsular crystalline lens extraction by phacoemulsification'),
(198,'Extracapsular crystalline lens extraction by mechanical phacofragmentation'),
(199,'Other extracapsular crystalline lens extraction'),
(200,'Other extraction of crystalline lens'),
(201,'Removal of after cataract'),
(202,'Other application, insertion or removal procedures on lens'),
(203,'Other procedures on lens'),
(204,'Aspiration of aqueous or vitreous'),
(205,'Other application, insertion or removal procedures on aqueous or vitreous'),
(206,'Destruction procedures on aqueous or vitreous'),
(207,'Vitrectomy'),
(208,'Other procedures on vitreous'),
(209,'Application, insertion or removal procedures on retina, choroid or posterior chamber'),
(210,'Incision procedures on retina, choroid or posterior chamber'),
(211,'Destruction procedures on retina, choroid or posterior chamber'),
(212,'Repair of retinal detachment'),
(213,'Revision procedures on retina, choroid or posterior chamber'),
(214,'Other procedures on retina, choroid or posterior chamber'),
(215,'Excision procedures on extraocular muscle'),
(216,'Strabismus repair'),
(217,'Other repair of extraocular muscle'),
(218,'Revision procedures on extraocular muscle'),
(219,'Reoperation procedures on extraocular muscle'),
(220,'Other procedures on extraocular muscle or tendon'),
(221,'Application, insertion or removal procedures on orbit'),
(222,'Orbitotomy'),
(223,'Other incision procedures on orbit'),
(224,'Orbitotomy with biopsy or excision'),
(225,'Exenteration of orbit'),
(226,'Other excision procedures on orbit'),
(227,'Orbitotomy with removal and replacement of bone'),
(228,'Other repair procedures on orbit'),
(229,'Other procedures on orbit'),
(230,'Application, insertion or removal procedures on eyelid'),
(231,'Incision procedures on eyelid'),
(232,'Biopsy of eyelid'),
(233,'Other excision procedures on eyelid'),
(234,'Graft to eyelid'),
(235,'Canthoplasty'),
(236,'Other repair procedures on eyelid'),
(237,'Reconstruction procedure on eyelid'),
(238,'Procedures for correction of trichiasis'),
(239,'Procedures for ectropion or entropion'),
(240,'Other procedures on eyelid'),
(241,'Probing of lacrimal passages'),
(242,'Insertion, replacement or removal of nasolacrimal tube'),
(243,'Other application, insertion or removal procedures on lacrimal system'),
(244,'Incision procedures on lacrimal system'),
(245,'Destruction procedures on lacrimal system'),
(246,'Excision procedures on lacrimal system'),
(247,'Repair procedures on lacrimal system'),
(248,'Reoperation procedures on lacrimal passages'),
(249,'Procedures for establishment of lacrimal patency'),
(250,'Other procedures on lacrimal system'),
(251,'Application, insertion or removal procedures on conjunctiva'),
(252,'Incision procedures on conjunctiva'),
(253,'Destruction procedures on conjunctiva'),
(254,'Excision procedures on conjunctiva'),
(255,'Repair procedures on conjunctiva'),
(256,'Other procedures on conjunctiva'),
(300,'Examination procedures on external ear'),
(301,'Application, insertion or removal procedures on external ear'),
(302,'Incision procedures on auditory canal'),
(303,'Excision procedures on external ear'),
(304,'Repair procedures on external ear'),
(305,'Reconstruction procedures on external ear'),
(306,'Other procedures on external ear'),
(307,'Examination procedures on eardrum or middle ear'),
(308,'Application, insertion or removal procedures on eardrum or middle ear'),
(309,'Myringotomy'),
(310,'Other incision procedures on eardrum or middle ear'),
(311,'Destruction procedures on eardrum or middle ear'),
(312,'Excision procedures on eardrum or middle ear'),
(313,'Myringoplasty'),
(314,'Other repair procedures on eardrum or middle ear'),
(315,'Reconstruction procedures on eardrum or middle ear'),
(316,'Other procedures on eardrum or middle ear'),
(317,'Excision procedures on ossicles of ear'),
(318,'Repair procedures on ossicles of ear'),
(319,'Reconstruction procedures on ossicles of ear'),
(320,'Other procedures on ossicles of ear'),
(321,'Application, insertion or removal procedures on mastoid or temporal bone'),
(322,'Incision procedures on mastoid or temporal bone'),
(323,'Mastoidectomy'),
(324,'Other excision procedures on mastoid or temporal bone'),
(325,'Repair procedures on mastoid or temporal bone'),
(326,'Reconstruction procedures on mastoid or temporal bone'),
(327,'Revision procedures on mastoid or temporal bone'),
(328,'Other procedures on mastoid or temporal bone'),
(329,'Application, insertion or removal procedures on inner ear'),
(330,'Incision procedures on inner ear'),
(331,'Excision procedures on inner ear'),
(332,'Repair procedures on inner ear'),
(333,'Other procedures on inner ear'),
(370,'Examination procedures on nose'),
(371,'Application, insertion or removal procedures on nose'),
(372,'Incision procedures on nose'),
(373,'Arrest of nasal haemorrhage'),
(374,'Other destruction procedures on nose'),
(375,'Biopsy of nasal cavity'),
(376,'Excision procedures on nasal turbinates'),
(377,'Removal of intranasal lesion'),
(378,'Other excision procedures on nose'),
(379,'Repair of nasal septum'),
(380,'Other repair procedures on nose'),
(381,'Other procedures on nose'),
(382,'Application, insertion or removal procedures on nasal sinuses'),
(383,'Incision procedures on nasal sinuses'),
(384,'Biopsy of nasal sinuses'),
(385,'Intranasal removal of polyp from nasal sinuses'),
(386,'Other excision procedures on nasal sinuses'),
(387,'Maxillary antrostomy'),
(388,'Other repair procedures on nasal sinuses'),
(389,'Other procedures on nasal sinuses'),
(390,'Incision procedures on tongue'),
(391,'Destruction procedures on tongue'),
(392,'Excision procedures on tongue'),
(393,'Repair procedures on tongue'),
(394,'Other procedures on tongue'),
(395,'Incision procedures on salivary gland or duct'),
(396,'Destruction procedures on salivary gland or duct'),
(397,'Excision procedures on salivary gland or duct'),
(398,'Repair procedures on salivary gland or duct'),
(399,'Other procedures on salivary gland or duct'),
(400,'Application, insertion or removal procedures on mouth, palate or uvula'),
(401,'Incision procedures on mouth, palate or uvula'),
(402,'Biopsy of oral cavity or soft palate'),
(403,'Excision of lesion of mouth or palate'),
(404,'Other excision procedures on mouth, palate or uvula'),
(405,'Uvulopalatopharyngoplasty'),
(406,'Other repair procedures on mouth, palate or uvula'),
(407,'Revision procedures on mouth, palate or uvula'),
(408,'Other procedures on mouth, palate or uvula'),
(409,'Incision procedures on tonsils or adenoids'),
(410,'Destruction procedures on tonsils or adenoids'),
(411,'Biopsy of tonsils or adenoids'),
(412,'Tonsillectomy or adenoidectomy'),
(413,'Other excision procedures on tonsils or adenoids'),
(414,'Other repair procedures on tonsils or adenoids'),
(415,'Other procedures on tonsils or adenoids'),
(416,'Examination procedures on pharynx'),
(417,'Application, insertion or removal procedures on pharynx'),
(418,'Incision procedures on pharynx'),
(419,'Destruction procedures on pharynx'),
(420,'Pharyngectomy'),
(421,'Other excision procedures on pharynx'),
(422,'Other procedures on pharynx'),
(450,'Dental examination'),
(451,'Dental radiological examination and interpretation'),
(452,'Other dental diagnostic services'),
(453,'Dental prophylaxis and bleaching'),
(454,'Topical application of remineralisation and/or cariostatic agent'),
(455,'Other preventative dental service'),
(456,'Periodontic interventions'),
(457,'Nonsurgical removal of tooth'),
(458,'Surgical removal of tooth'),
(459,'Surgery for prosthetics'),
(460,'General surgical dental procedure'),
(461,'Other dental surgical procedure'),
(462,'Pulp treatment'),
(463,'Periradicular surgery'),
(464,'Other endodontic service'),
(465,'Metallic restoration'),
(466,'Tooth-coloured restoration'),
(467,'BLOCK NOT USED IN ACHI 9th EDITION'),
(468,'BLOCK NOT USED IN ACHI 9th EDITION'),
(469,'Other restorative dental service'),
(470,'Crown'),
(471,'Bridge'),
(472,'Other dental service on crown and bridge'),
(473,'Implant prosthesis'),
(474,'Denture or denture component'),
(475,'Denture maintenance'),
(476,'Denture repair'),
(477,'Other prosthodontic service'),
(478,'BLOCK NOT USED IN ACHI 9th EDITION'),
(479,'Removable orthodontic appliance'),
(480,'Fixed orthodontic appliance'),
(481,'Extraoral appliance'),
(482,'Orthodontic attachment'),
(483,'Other orthodontic service'),
(484,'Dental emergency'),
(485,'Dental drug therapy'),
(486,'BLOCK NOT USED IN ACHI 9th EDITION'),
(487,'BLOCK NOT USED IN ACHI 9th EDITION'),
(488,'BLOCK NOT USED IN ACHI 9th EDITION'),
(489,'Occlusal therapy'),
(490,'Miscellaneous dental services'),
(520,'Examination procedures on larynx'),
(521,'Application, insertion or removal procedures on larynx'),
(522,'Incision procedures on larynx'),
(523,'Laryngoscopy with excision'),
(524,'Laryngectomy'),
(525,'Other excision procedures on larynx'),
(526,'Laryngoplasty'),
(527,'Laryngofissure'),
(528,'Other repair procedures on larynx'),
(529,'Reconstruction procedures on larynx'),
(530,'Reoperation procedures on larynx'),
(531,'Other procedures on larynx'),
(532,'Examination procedures on trachea'),
(533,'Application, insertion or removal procedures on trachea'),
(534,'Excision procedures on trachea'),
(535,'Cricothyrostomy'),
(536,'Tracheostomy'),
(537,'Resection of endotracheal lesion with repair'),
(538,'Resection of endotracheal stricture with repair'),
(539,'Other repair procedures on trachea'),
(540,'Reconstruction procedures on trachea'),
(541,'Revision procedures on trachea'),
(542,'Other procedures on trachea'),
(543,'Examination procedures on bronchus'),
(544,'Endoscopic biopsy, broncho-alveolar lavage or removal of foreign body from bronchus'),
(545,'Other excision procedures on bronchus'),
(546,'Repair procedures on bronchus'),
(547,'Other procedures on bronchus'),
(548,'Application, insertion or removal procedures on lung or pleura'),
(549,'Incision procedures on lung or pleura'),
(550,'Biopsy of lung or pleura'),
(551,'Partial resection of lung'),
(552,'Lobectomy of lung'),
(553,'Pneumonectomy'),
(554,'Other excision procedures on lung or pleura'),
(555,'Transplantation of lung'),
(556,'Other repair procedures on lung or pleura'),
(557,'Revision procedures on lung or pleura'),
(558,'Other procedures on lung or pleura'),
(559,'Examination procedures on chest wall, mediastinum or diaphragm'),
(560,'Application, insertion or removal procedures on chest wall, mediastinum or diaphragm'),
(561,'Incision procedures on chest wall, mediastinum or diaphragm'),
(562,'Destruction procedures on chest wall, mediastinum or diaphragm'),
(563,'Excision procedures on chest wall, mediastinum or diaphragm'),
(564,'Repair of pectus carinatum or excavatum'),
(565,'Thoracoplasty'),
(566,'Other repair procedures on chest wall, mediastinum or diaphragm'),
(567,'Other procedures on chest wall, mediastinum or diaphragm'),
(568,'Airway management'),
(569,'Ventilatory support'),
(570,'Noninvasive ventilatory support'),
(571,'Combined ventilatory support'),
(600,'Incision procedures on atrium'),
(601,'Destruction procedures on atrium'),
(602,'Excision procedures on atrium'),
(603,'Repair procedures on atrium'),
(604,'Reconstruction procedures on atrium'),
(605,'Revision procedures on atrium'),
(606,'Other procedures on atrium'),
(607,'Examination procedures on ventricle'),
(608,'Application, insertion or removal procedures on ventricle'),
(609,'Destruction procedures on ventricle'),
(610,'Ventricular myectomy'),
(611,'Excision of ventricular aneurysm'),
(612,'Other excision procedures on ventricle'),
(613,'Baffle or conduit procedures'),
(614,'Other repair procedures on ventricle'),
(615,'Other procedures on ventricle'),
(616,'Excision procedures on septum'),
(617,'Closure of atrial septal defect'),
(618,'Closure of ventricular septal defect'),
(619,'Other repair procedures on septum'),
(620,'Other procedures on septum'),
(621,'Incision procedures on aortic valve'),
(622,'Repair of aortic valve'),
(623,'Replacement of aortic valve'),
(624,'Other procedures on aortic valve'),
(625,'Incision procedures on mitral valve'),
(626,'Repair of mitral valve'),
(627,'Mitral valve annuloplasty'),
(628,'Replacement of mitral valve'),
(629,'Reconstruction procedures on mitral valve'),
(630,'Other procedures on mitral valve'),
(631,'Incision procedures on tricuspid valve'),
(632,'Repair of tricuspid valve'),
(633,'Tricuspid valve annuloplasty'),
(634,'Replacement of tricuspid valve'),
(635,'Other procedures on tricuspid valve'),
(636,'Incision procedures on pulmonary valve'),
(637,'Repair or replacement of pulmonary valve'),
(638,'Other procedures on pulmonary valve'),
(639,'Incision procedures on myocardium'),
(640,'Excision procedures on myocardium'),
(641,'Repair procedures on myocardium'),
(642,'Myocardial preservation'),
(643,'Drainage of heart'),
(644,'Other incision procedures on pericardium'),
(645,'Biopsy of pericardium'),
(646,'Other excision procedures on pericardium'),
(647,'Insertion of temporary transvenous electrode for cardiac pacemaker or defibrillator'),
(648,'Insertion of permanent transvenous electrode for cardiac pacemaker or defibrillator'),
(649,'Insertion of other electrode or patch for cardiac pacemaker or defibrillator'),
(650,'Insertion of cardiac pacemaker generator'),
(651,'BLOCK NOT USED IN ACHI 9th EDITION'),
(652,'BLOCK NOT USED IN ACHI 9th EDITION'),
(653,'Insertion of cardiac defibrillator generator'),
(654,'Adjustment, replacement or removal of electrode for cardiac pacemaker or defibrillator'),
(655,'Adjustment, replacement or removal of cardiac pacemaker generator'),
(656,'Adjustment, replacement or removal of cardiac defibrillator generator'),
(657,'Other application, insertion or removal procedures on other sites of heart'),
(658,'BLOCK NOT USED IN ACHI 9th EDITION'),
(659,'Removal of donor heart or lung'),
(660,'Transplantation of heart or lung'),
(661,'Other repair procedures on other sites of heart'),
(662,'Reconstruction procedures on other sites of heart'),
(663,'Revision procedures on other sites of heart'),
(664,'Reoperation procedures on other sites of heart'),
(665,'Electrophysiological studies [EPS]'),
(666,'Other procedures on other sites of heart'),
(667,'Cardiac catheterisation'),
(668,'Coronary angiography'),
(669,'Excision procedures on coronary arteries'),
(670,'Transluminal coronary angioplasty'),
(671,'Transluminal coronary angioplasty with stenting'),
(672,'Coronary artery bypass - saphenous vein graft'),
(673,'Coronary artery bypass - other vein graft'),
(674,'Coronary artery bypass - left internal mammary artery [LIMA] graft'),
(675,'Coronary artery bypass - right internal mammary artery [RIMA] graft'),
(676,'Coronary artery bypass - radial artery graft'),
(677,'Coronary artery bypass - epigastric artery graft'),
(678,'Coronary artery bypass - other artery graft'),
(679,'Coronary artery bypass - other graft'),
(680,'Reoperation procedures on coronary arteries'),
(681,'Other procedures on coronary arteries'),
(682,'Application, insertion or removal procedures on aorta'),
(683,'BLOCK NOT USED IN ACHI 9th EDITION'),
(684,'Repair of ascending thoracic aorta'),
(685,'Repair of aortic arch and ascending thoracic aorta'),
(686,'Repair of descending thoracic aorta'),
(687,'Replacement of ascending thoracic aorta'),
(688,'Replacement of aortic arch and ascending thoracic aorta'),
(689,'Replacement of descending thoracic aorta'),
(690,'Closure of patent ductus arteriosus'),
(691,'Closure of cardiac collateral vessel'),
(692,'BLOCK NOT USED IN ACHI 9th EDITION'),
(693,'Repair procedures on aorta'),
(694,'Arterial catheterisation'),
(695,'Exploration of artery'),
(696,'Other incision procedures on artery'),
(697,'Interruption of artery'),
(698,'Other destruction procedures on artery'),
(699,'Biopsy of peripheral artery'),
(700,'Endarterectomy'),
(701,'Endarterectomy to prepare site for anastomosis'),
(702,'Arterial embolectomy or thrombectomy'),
(703,'Embolectomy or thrombectomy of an arterial bypass graft'),
(704,'Arterial atherectomy'),
(705,'Resection of lesion of carotid artery'),
(706,'Resection of recurrent lesion of carotid artery'),
(707,'Patch graft of artery'),
(708,'Direct closure of artery'),
(709,'Repair of artery by anastomosis'),
(710,'Repair of artery by interposition graft'),
(711,'Arterial bypass graft using vein'),
(712,'Arterial bypass graft using synthetic material'),
(713,'Arterial bypass graft using composite, sequential or crossover graft'),
(714,'Repair of aneurysm of neck, intra-abdominal area or extremities'),
(715,'Replacement of aneurysm with graft'),
(716,'Repair of aorto-enteric fistula'),
(717,'Repair procedures on pulmonary artery for congenital heart disease'),
(718,'Other repair procedures on arteries'),
(719,'BLOCK NOT USED IN ACHI 9th EDITION'),
(720,'Other procedures on arteries'),
(721,'Application of external stent to vein'),
(722,'Injection of varicose veins'),
(723,'Other application, insertion or removal procedures on veins'),
(724,'Exploration of vein'),
(725,'Other incision procedures on veins'),
(726,'Interruption of vein'),
(727,'Interruption of varicose veins of lower limb'),
(728,'Other destruction procedures on veins'),
(729,'Venous thrombectomy'),
(730,'Procurement of vein'),
(731,'Patch graft of vein'),
(732,'Direct closure of vein'),
(733,'Repair of vein by anastomosis'),
(734,'Repair of vein by interposition graft'),
(735,'Venous bypass graft using vein or synthetic material'),
(736,'Other repair procedures on veins'),
(737,'Reoperation procedures on veins'),
(738,'Venous catheterisation'),
(739,'Other procedures on veins'),
(740,'Examination procedures on other vascular sites'),
(741,'Surgical peripheral arterial or venous catheterisation'),
(742,'Other application, insertion or removal procedures on other vascular sites'),
(743,'Destruction of vascular lesions'),
(744,'Laser photocoagulation of cutaneous vascular lesion'),
(745,'Interruption of feeding vessels of arteriovenous fistula'),
(746,'Other destruction procedures on vascular sites'),
(747,'Biopsy of blood vessel'),
(748,'Excision of vascular anomaly'),
(749,'BLOCK NOT USED IN ACHI 9th EDITION'),
(750,'Excision of arteriovenous fistula of neck'),
(751,'Excision of arteriovenous fistula of limb'),
(752,'Excision of arteriovenous fistula of abdomen'),
(753,'Other excision procedures on vascular sites'),
(754,'Transluminal balloon angioplasty'),
(755,'BLOCK NOT USED IN ACHI 9th EDITION'),
(756,'BLOCK NOT USED IN ACHI 9th EDITION'),
(757,'BLOCK NOT USED IN ACHI 9th EDITION'),
(758,'Peripheral laser angioplasty'),
(759,'Repair of arteriovenous fistula of neck'),
(760,'Repair of arteriovenous fistula of extremity'),
(761,'Repair of arteriovenous fistula of abdomen'),
(762,'Other repair procedures on vascular sites'),
(763,'Reoperation procedures on other vascular sites'),
(764,'Procedures for external arteriovenous shunt'),
(765,'Procedures for surgically created arteriovenous fistula'),
(766,'Vascular access device'),
(767,'BLOCK NOT USED IN ACHI 9th EDITION'),
(768,'Transcatheter embolisation of blood vessels'),
(777,'Other procedures on arteries and veins'),
(800,'Biopsy of bone marrow'),
(801,'Other excision procedures on bone marrow'),
(802,'Bone marrow/stem cell transplantation'),
(803,'Other procedures on bone marrow'),
(804,'Incision procedures on lymphatic structure'),
(805,'Biopsy of lymphatic structure'),
(806,'Excision procedures on lymph node of neck'),
(807,'Excision of internal mammary lymph node'),
(808,'Excision procedures on lymph node of axilla'),
(809,'Excision procedures on lymph node of groin'),
(810,'Excision procedures on lymph nodes for gynaecological malignancy'),
(811,'Excision procedures on lymph node of other sites'),
(812,'Other procedures on lymphatic structures'),
(813,'Incision procedures on spleen'),
(814,'Biopsy of spleen'),
(815,'Other excision procedures on spleen'),
(816,'Repair of spleen'),
(817,'Other procedures on spleen'),
(850,'Oesophagoscopy'),
(851,'Endoscopic administration of agent into lesion of oesophagus'),
(852,'Removal of foreign body from oesophagus'),
(853,'Other application, insertion or removal procedures on oesophagus'),
(854,'Oesophagogastric myotomy'),
(855,'Other incision procedures on oesophagus'),
(856,'Destruction procedures on oesophagus'),
(857,'Resection of oesophagus, paediatric'),
(858,'Oesophagectomy by abdominal and thoracic mobilisation'),
(859,'Oesophagectomy by abdominal and cervical mobilisation'),
(860,'Oesophagectomy by abdominal and transthoracic mobilisation'),
(861,'Other excision procedures on oesophagus'),
(862,'Dilation of oesophagus'),
(863,'Oesophagogastric myotomy and repair, laparoscopic'),
(864,'Oesophagogastric myotomy and repair, abdominal'),
(865,'Oesophagogastric myotomy and repair, thoracic'),
(866,'Repair of oesophageal atresia'),
(867,'Other repair procedures on oesophagus'),
(868,'Reconstruction procedures on oesophagus'),
(869,'Other procedures on oesophagus'),
(870,'Application, insertion or removal procedures on stomach'),
(871,'Gastrotomy'),
(872,'Vagotomy'),
(873,'Other incision procedures on stomach'),
(874,'Destruction procedures on stomach'),
(875,'Partial gastrectomy'),
(876,'Partial gastrectomy following previous procedure for peptic ulcer disease'),
(877,'Selective vagotomy with partial gastrectomy'),
(878,'Selective vagotomy with partial gastrectomy following previous procedure for peptic ulcer disease'),
(879,'Other gastrectomy'),
(880,'Other excision procedures on stomach'),
(881,'Gastrostomy, gastro-enterostomy or gastro-gastrostomy'),
(882,'Endoscopic dilation of gastric stricture'),
(883,'Pyloroplasty'),
(884,'Other vagotomy with repair'),
(885,'BLOCK NOT USED IN ACHI 9th EDITION'),
(886,'Fundoplasty'),
(887,'Other repair procedures on stomach'),
(888,'Reconstruction procedures on stomach'),
(889,'Procedures for obesity'),
(890,'Other procedures on stomach'),
(891,'Exploration of small intestine'),
(892,'Application, insertion or removal procedures on small intestine'),
(893,'Enterotomy'),
(894,'Other incision procedures on small intestine'),
(895,'Resection of small intestine'),
(896,'Other excision procedures on small intestine'),
(897,'Stomas of small intestine'),
(898,'Reduction procedures on small intestine'),
(899,'Closure of stoma of small intestine'),
(900,'Repair of small intestine'),
(901,'Other repair procedures on small intestine'),
(902,'Revision of stoma and ileostomy reservoir'),
(903,'Other procedures on small intestine'),
(904,'Rigid sigmoidoscopy'),
(905,'Fibreoptic colonoscopy'),
(906,'Application, insertion or removal procedures on large intestine'),
(907,'Incision procedures on large intestine'),
(908,'Destruction procedures on large intestine'),
(909,'Biopsy of large intestine'),
(910,'Rigid sigmoidoscopy with excision'),
(911,'Fibreoptic colonoscopy with excision'),
(912,'BLOCK NOT USED IN ACHI 9th EDITION'),
(913,'Colectomy'),
(914,'Other excision procedures on large intestine'),
(915,'Other stomas of large intestine'),
(916,'Reduction procedures on large intestine'),
(917,'Other repair of large intestine'),
(918,'Revision procedures on large intestine'),
(919,'BLOCK NOT USED IN ACHI 9th EDITION'),
(920,'BLOCK NOT USED IN ACHI 9th EDITION'),
(921,'BLOCK NOT USED IN ACHI 9th EDITION'),
(922,'BLOCK NOT USED IN ACHI 9th EDITION'),
(923,'BLOCK NOT USED IN ACHI 9th EDITION'),
(924,'Procedures for exomphalos'),
(925,'Other procedures on large intestine'),
(926,'Appendicectomy'),
(927,'Other procedures on appendix'),
(928,'Examination procedures on rectum or anus'),
(929,'Application, insertion or removal procedures on rectum or anus'),
(930,'Incision procedures on rectum or anus'),
(931,'Destruction procedures on rectum or anus'),
(932,'Rectal or anal biopsy'),
(933,'Excision of lesion or tissue of rectum or anus'),
(934,'Rectosigmoidectomy or proctectomy'),
(935,'Anterior resection of rectum'),
(936,'Total proctocolectomy'),
(937,'Other excision procedures on rectum or anus'),
(938,'Anoplasty or anorectoplasty'),
(939,'Repair of cloacal exstrophy'),
(940,'Other repair procedures on rectum or anus'),
(941,'Procedures for haemorrhoids'),
(942,'Other procedures on rectum or anus'),
(944,'BLOCK NOT USED IN ACHI 9th EDITION'),
(947,'BLOCK NOT USED IN ACHI 9th EDITION'),
(948,'BLOCK NOT USED IN ACHI 9th EDITION'),
(951,'Application, insertion or removal procedures on liver'),
(952,'Incision procedures on liver'),
(953,'Excision procedures on liver'),
(954,'Repair procedures on liver'),
(955,'Procedures for hydatid cyst of liver'),
(956,'Other procedures on liver'),
(957,'Examination of gallbladder or biliary tract'),
(958,'Stenting of biliary tract'),
(959,'Endoscopic and percutaneous removal of calculus'),
(960,'Removal and replacement of biliary stent'),
(961,'Other application, insertion or removal procedures on gallbladder or bile ducts'),
(962,'Destruction procedures on biliary tract and gallbladder'),
(963,'Incision of gallbladder, biliary tract or sphincter of Oddi'),
(964,'Biopsy of gallbladder, bile ducts or sphincter of Oddi'),
(965,'Cholecystectomy'),
(966,'Resection of hepatic duct or porta hepatis'),
(967,'Resection of choledochal cyst'),
(968,'Other excision procedures on gallbladder, bile ducts or sphincter of Oddi'),
(969,'Stoma of gallbladder or bile duct'),
(970,'Roux-en-Y bypass'),
(971,'Other repair of sphincter of Oddi, gallbladder or biliary tract'),
(972,'Procedures for portal hypertension'),
(973,'Other procedures on gallbladder or biliary tract'),
(974,'Examination of pancreas'),
(975,'Application, insertion or removal procedures on pancreas'),
(976,'Incision procedures on pancreas'),
(977,'Biopsy of pancreas'),
(978,'Pancreatectomy'),
(979,'Other excision procedures on pancreas or pancreatic duct'),
(980,'Anastomosis of pancreas'),
(981,'Other repair procedures on pancreas'),
(982,'Other procedures on pancreas'),
(983,'Application, insertion or removal procedures on abdomen, peritoneum or omentum'),
(984,'Laparoscopy'),
(985,'Laparotomy'),
(986,'Division of abdominal adhesions'),
(987,'Other incision procedures on abdomen, peritoneum or omentum'),
(988,'Biopsy of abdomen, peritoneum or omentum'),
(989,'Other excision procedures on abdomen, peritoneum or omentum'),
(990,'Repair of inguinal hernia'),
(991,'Repair of femoral hernia'),
(992,'Repair of umbilical, epigastric or linea alba hernia'),
(993,'Repair of incisional hernia'),
(994,'Repair of parastomal hernia'),
(995,'BLOCK NOT USED IN ACHI 9th EDITION'),
(996,'Repair of other abdominal wall hernia'),
(997,'Repair of incarcerated, obstructed or strangulated hernia'),
(998,'Repair of diaphragmatic hernia'),
(999,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1000,'Other repair procedures on abdomen, peritoneum or omentum'),
(1001,'Revision procedures on abdomen, peritoneum or omentum'),
(1002,'Procedures for hydatid cyst of peritoneum or abdominal organs'),
(1003,'Procedures for gastroschisis'),
(1004,'Other procedures on abdomen, peritoneum or omentum'),
(1005,'Panendoscopy'),
(1006,'Panendoscopy with removal of foreign body'),
(1007,'Panendoscopy with destruction'),
(1008,'Panendoscopy with excision'),
(1009,'Repair procedures on other and multiple sites of digestive system'),
(1010,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1011,'Other procedures on digestive system'),
(1040,'Examination procedures on kidney'),
(1041,'Manipulation or extraction of calculus of kidney'),
(1042,'Other application, insertion or removal procedures on kidney'),
(1043,'Percutaneous nephroscopy'),
(1044,'Nephrolithotomy with removal of calculi'),
(1045,'Other incision procedures on kidney'),
(1046,'Destruction procedures on kidney'),
(1047,'Biopsy of kidney'),
(1048,'Partial nephrectomy'),
(1049,'Complete nephrectomy'),
(1050,'Complete nephrectomy for transplantation'),
(1051,'Complete nephrectomy for removal of transplanted kidney'),
(1052,'Complete nephrectomy complicated by previous surgery on same kidney'),
(1053,'Radical nephrectomy'),
(1054,'Nephroureterectomy'),
(1055,'Other excision procedures on kidney'),
(1056,'Nephrostomy or pyelostomy'),
(1057,'Pyeloplasty'),
(1058,'Kidney transplantation'),
(1059,'Other repair procedures on kidney'),
(1060,'Haemodialysis'),
(1061,'Peritoneal dialysis'),
(1062,'Procedures for establishment or maintenance of peritoneal dialysis'),
(1063,'Other interventions for renal dialysis'),
(1064,'Other procedures on kidney'),
(1065,'Examination procedures on ureter'),
(1066,'Endoscopic ureteric catheterisation'),
(1067,'Endoscopic insertion, replacement or removal of ureteric stent'),
(1068,'Endoscopic manipulation or extraction of ureteric calculus'),
(1069,'Other application, insertion or removal procedures on ureter'),
(1070,'Exploration of ureter'),
(1071,'Ureterolysis'),
(1072,'Ureterolithotomy'),
(1073,'Other incision procedures on ureter'),
(1074,'Destruction procedures on ureter'),
(1075,'Biopsy of ureter'),
(1076,'Ureterectomy'),
(1077,'Other excision procedures on ureter'),
(1078,'Ureterolysis with repositioning of ureter'),
(1079,'Repair of divided ureter'),
(1080,'Transplantation of ureter into skin'),
(1081,'Transplantation of ureter into other ureter'),
(1082,'Transplantation of ureter into intestine'),
(1084,'Reimplantation of ureter into bladder'),
(1085,'Reimplantation of ureter into bladder with repair'),
(1086,'Other repair procedures on ureter'),
(1087,'Revision procedures on ureter'),
(1088,'Other procedures on ureter'),
(1089,'Examination procedures on bladder'),
(1090,'Urinary catheterisation'),
(1091,'Implantation or removal of electronic bladder stimulator'),
(1092,'Other application, insertion or removal procedures on bladder'),
(1093,'Cystotomy'),
(1094,'Cystolithotomy'),
(1095,'Other incision procedures on bladder'),
(1096,'Destruction procedures on bladder'),
(1097,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1098,'Biopsy of bladder'),
(1099,'Removal of foreign body from bladder'),
(1100,'Endoscopic resection of bladder lesion or tissue'),
(1101,'Endoscopic resection of bladder neck'),
(1102,'Cystectomy'),
(1103,'Other excision procedures on bladder'),
(1104,'Repair of ruptured bladder'),
(1105,'Closure of fistula of bladder'),
(1106,'Repair of bladder exstrophy'),
(1107,'Enlargement of bladder'),
(1108,'Other repair procedures on bladder'),
(1109,'Procedures for male stress incontinence'),
(1110,'Procedures for female stress incontinence'),
(1111,'Other procedures on bladder'),
(1112,'Examination procedures on urethra'),
(1113,'Insertion, replacement or removal of artificial urinary sphincter'),
(1114,'Other application, insertion or removal procedures on urethra'),
(1115,'Incision procedures on urethra'),
(1116,'Destruction procedures on urethra'),
(1117,'Biopsy of urethra'),
(1118,'Other excision procedures on urethra'),
(1119,'Closure of fistula of urethra'),
(1120,'Repair of laceration of urethra'),
(1121,'Urethroplasty'),
(1122,'Other repair procedures on urethra'),
(1123,'Reconstruction procedures on urethra'),
(1124,'Revision procedures on urethra'),
(1125,'Other procedures on urethra'),
(1126,'Destruction procedures on other sites of urinary system'),
(1127,'Incision procedures on other sites of urinary system'),
(1128,'Excision procedures on other sites of urinary system'),
(1129,'Other procedures on urinary system'),
(1160,'Application, insertion or removal procedures on prostate or seminal vesicle'),
(1161,'Incision procedures on prostate or seminal vesicle'),
(1162,'Destruction of tissue of prostate'),
(1163,'Closed biopsy of prostate or seminal vesicle'),
(1164,'Open biopsy of prostate or seminal vesicle'),
(1165,'Transurethral prostatectomy'),
(1166,'Other closed prostatectomy'),
(1167,'Open prostatectomy'),
(1168,'Other excision procedures on prostate or seminal vesicle'),
(1169,'Repair procedures on prostate or seminal vesicle'),
(1170,'Other procedures on prostate or seminal vesicle'),
(1171,'Application, insertion or removal procedures on scrotum or tunica vaginalis'),
(1172,'Exploration of scrotum'),
(1173,'Exploration of scrotal contents with biopsy'),
(1174,'Other excision procedures on scrotum or tunica vaginalis'),
(1175,'Repair procedures on scrotum or tunica vaginalis'),
(1176,'Other procedures on scrotum or tunica vaginalis'),
(1177,'Application, insertion or removal procedures on testis, vas deferens, epididymis or spermatic cord'),
(1178,'Incision procedures on testis, vas deferens, epididymis or spermatic cord'),
(1179,'Destruction procedures on testis, vas deferens, epididymis or spermatic cord'),
(1180,'Biopsy of testis, vas deferens, epididymis or spermatic cord'),
(1181,'Excision of lesion of testis, epididymis or spermatic cord'),
(1182,'Excision of spermatic cord'),
(1183,'Vasectomy and epididymectomy'),
(1184,'Orchidectomy'),
(1185,'Vasovasostomy and vasoepididymostomy'),
(1186,'Orchidopexy for undescended testis'),
(1187,'Other repair procedures on testis, vas deferens, epididymis or spermatic cord'),
(1188,'Revision procedures on testis, vas deferens, epididymis or spermatic cord'),
(1189,'Other procedures on testis, vas deferens, epididymis or spermatic cord'),
(1190,'Examination procedures on penis'),
(1191,'Insertion or removal of artificial erection device'),
(1192,'Other application, insertion or removal procedures on penis'),
(1193,'Decompression of priapism'),
(1194,'Other incision procedures on penis'),
(1195,'Destruction procedures on penis'),
(1196,'Excision procedures on penis'),
(1197,'Correction of chordee of penis'),
(1198,'Repair of hypospadias'),
(1199,'Repair of epispadias'),
(1200,'Other repair procedures on penis'),
(1201,'Revision of artificial erection device'),
(1202,'Other procedures on penis'),
(1203,'Other procedures on male genital organs'),
(1230,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1231,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1232,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1234,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1240,'Application, insertion or removal procedures on ovary'),
(1241,'Incision procedures on ovary'),
(1242,'Biopsy of ovary'),
(1243,'Oophorectomy'),
(1244,'Other excision procedures on ovary'),
(1245,'Transposition of ovary'),
(1246,'Other repair procedures on ovary'),
(1247,'Other procedures on ovary'),
(1248,'Application, insertion or removal procedures on fallopian tube'),
(1249,'Incision procedures on fallopian tube'),
(1250,'Biopsy of fallopian tube'),
(1251,'Salpingectomy'),
(1252,'Salpingo-oophorectomy'),
(1253,'Salpingoplasty'),
(1254,'Anastomosis of fallopian tube'),
(1255,'Other repair procedures on fallopian tube'),
(1256,'Procedures for management of ectopic pregnancy'),
(1257,'Procedures for female sterilisation'),
(1258,'Other procedures on fallopian tube'),
(1259,'Examination procedures on uterus'),
(1260,'Insertion or removal of intrauterine device'),
(1261,'Other application, insertion or removal procedures on uterus'),
(1262,'Incision procedures on uterus'),
(1263,'Destruction procedures on uterus'),
(1264,'Biopsy of endometrium'),
(1265,'Curettage and evacuation of uterus'),
(1266,'Excision of lesion of uterus'),
(1267,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1268,'Abdominal hysterectomy'),
(1269,'Vaginal hysterectomy'),
(1270,'Other excision procedures on uterus'),
(1271,'Uterine suspension procedures'),
(1272,'Reconstruction procedures on uterus and supporting structures'),
(1273,'Other procedures on uterus'),
(1274,'Application, insertion or removal procedures on cervix'),
(1275,'Destruction procedures on cervix'),
(1276,'Excision procedures on cervix'),
(1277,'Repair procedures on cervix'),
(1278,'Other procedures on cervix'),
(1279,'Examination procedures on vagina'),
(1280,'Incision procedures on vagina'),
(1281,'Destruction procedures on vagina'),
(1282,'Excision procedures on vagina'),
(1283,'Repair of prolapse of uterus, pelvic floor or enterocele'),
(1284,'Repair of vaginal fistula'),
(1285,'Vaginal suspension procedures'),
(1286,'Other repair procedures on vagina'),
(1287,'Reconstruction procedures on vagina'),
(1288,'Other procedures on vagina'),
(1289,'Destruction procedures on vulva or perineum'),
(1290,'Incision procedures on vulva or perineum'),
(1291,'Biopsy of vulva or perineum'),
(1292,'Vulvectomy'),
(1293,'Other excision procedures on vulva, perineum or clitoris'),
(1294,'Repair procedures on vulva or perineum'),
(1295,'Other procedures on vulva or perineum'),
(1296,'Examination procedures on other gynaecological sites'),
(1297,'Procedures for reproductive medicine'),
(1298,'Procedures for anomalies of genitalia'),
(1299,'Other procedures on female genital organs'),
(1330,'Antepartum application, insertion or removal procedures'),
(1331,'Antepartum incision procedures'),
(1332,'Antepartum repair procedures'),
(1333,'Analgesia and anaesthesia during labour and delivery procedure'),
(1334,'Medical or surgical induction of labour'),
(1335,'Medical or surgical augmentation of labour'),
(1336,'Spontaneous vertex delivery'),
(1337,'Forceps delivery'),
(1338,'Vacuum extraction'),
(1339,'Breech delivery and extraction'),
(1340,'Caesarean section'),
(1341,'Fetal monitoring'),
(1342,'Manipulation of fetal position and presentation'),
(1343,'Other procedures associated with delivery'),
(1344,'Postpartum suture'),
(1345,'Postpartum evacuation of uterus'),
(1346,'Correction of inverted uterus'),
(1347,'Other postpartum procedures'),
(1360,'Application, insertion or removal procedures of head'),
(1361,'External fixation of mandible'),
(1362,'Exploration of temporomandibular joint'),
(1363,'Other incision procedures on maxilla or mandible'),
(1364,'Excision procedures on maxilla, mandible or temporomandibular joint'),
(1365,'Reduction of fracture of nasal bone'),
(1366,'Reduction of fracture of mandible or maxilla'),
(1367,'Reduction of fracture of mandibular or maxillary alveolar ridge'),
(1368,'Reduction of fracture of zygomatic bone'),
(1369,'Reduction of temporomandibular joint'),
(1370,'Reduction of fracture or dislocation of other facial bone'),
(1371,'Repair procedures on maxilla, mandible or temporomandibular joint'),
(1372,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1373,'Application, insertion or removal procedures of neck or thorax'),
(1374,'Incision procedures on neck or thorax'),
(1375,'Ostectomy of rib'),
(1376,'Other excision procedures on neck or thorax'),
(1377,'Reduction of fracture/dislocation of neck or thorax'),
(1378,'Repair procedures on neck or thorax'),
(1379,'Reoperation procedures on neck or thorax'),
(1380,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1381,'Immobilisation of fracture or dislocation of spine'),
(1382,'Biopsy of intervertebral disc and vertebra'),
(1383,'Excision of vertebra'),
(1384,'En bloc resection of lesion of soft tissue involving sacrum or spine'),
(1385,'Other excision procedures on spine (vertebral column)'),
(1386,'Manipulation of spine'),
(1387,'Closed reduction of fracture/dislocation of spine'),
(1388,'Open reduction of fracture/dislocation of spine'),
(1389,'Spinal fusion'),
(1390,'Internal fixation of spine'),
(1391,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1392,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1393,'Other spinal procedures'),
(1394,'Application, insertion or removal procedures on shoulder'),
(1395,'Incision procedures on shoulder'),
(1396,'Biopsy of shoulder'),
(1397,'Synovectomy or debridement of shoulder'),
(1398,'Ostectomy of clavicle or scapula'),
(1399,'Amputation of shoulder'),
(1400,'Other excision on shoulder'),
(1401,'Reduction of fracture of clavicle or shoulder'),
(1402,'Reduction of dislocation of clavicle, scapula or shoulder'),
(1403,'Arthrodesis of shoulder'),
(1404,'Other repair procedures on shoulder'),
(1405,'Reconstruction procedures on shoulder'),
(1406,'Revision procedures on shoulder'),
(1407,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1408,'Immobilisation of fracture of humerus'),
(1409,'Other application, insertion or removal procedures on humerus or elbow'),
(1410,'Incision procedures on humerus or elbow'),
(1411,'Biopsy of elbow'),
(1412,'Other excision procedures on humerus or elbow'),
(1413,'Closed reduction of fracture of humerus or elbow'),
(1414,'Open reduction of fracture of humerus or elbow'),
(1415,'Closed reduction of dislocation of humerus or elbow'),
(1416,'Open reduction of dislocation of humerus or elbow'),
(1417,'Bone graft to humerus'),
(1418,'Other repair procedures on humerus or elbow'),
(1419,'Revision procedures on humerus or elbow'),
(1420,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1421,'Immobilisation of fracture of shaft and distal radius or ulna'),
(1422,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1423,'Incision of fascia of forearm'),
(1424,'Incision of radius or ulna'),
(1425,'Other incision procedures on forearm'),
(1426,'Excision procedures on forearm'),
(1427,'Closed reduction of fracture of radius'),
(1428,'Closed reduction of fracture of ulna or olecranon'),
(1429,'Open reduction of fracture of radius'),
(1430,'Open reduction of fracture of ulna or olecranon'),
(1431,'Reduction of fracture of shaft of radius and ulna'),
(1432,'Open reduction of fracture of shaft of radius or ulna with dislocation'),
(1433,'Reduction of dislocation of radius or ulna'),
(1434,'Reduction of separated epiphysis of radius or ulna'),
(1435,'Bone graft to forearm'),
(1436,'Other repair procedures on forearm'),
(1437,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1438,'Other procedures on forearm'),
(1439,'Application, insertion or removal procedures on hand or wrist'),
(1440,'Incision procedures on muscle, tendon or fascia of hand'),
(1441,'Incision procedures on bone of hand'),
(1442,'Incision procedures on joint of hand'),
(1443,'Incision procedures on wrist'),
(1444,'Biopsy of wrist'),
(1445,'Synovectomy of joint of hand'),
(1446,'Synovectomy of tendon of hand or wrist'),
(1447,'Fasciectomy for Dupuytren''s contracture'),
(1448,'Amputation of wrist, hand or digit'),
(1449,'Other excision procedures on bone of hand'),
(1450,'Other excision procedures on hand'),
(1451,'Other excision procedures on wrist'),
(1452,'Closed reduction of fracture of carpus'),
(1453,'Closed reduction of fracture of metacarpus of hand'),
(1454,'Closed reduction of phalanx of hand'),
(1455,'Open reduction of fracture of carpus'),
(1456,'Open reduction of fracture of metacarpus of hand'),
(1457,'Open reduction of fracture of phalanx of hand'),
(1458,'Closed reduction of dislocation of joint of hand'),
(1459,'Open reduction of dislocation of joint of hand'),
(1460,'Arthrodesis of hand'),
(1461,'Bone graft of wrist, metacarpus or phalanx of hand'),
(1462,'Arthroplasty of interphalangeal joint of hand'),
(1463,'Arthroplasty of metacarpophalangeal joint'),
(1464,'Other arthroplasty of phalangeal joint of hand'),
(1465,'Repair of ligament or capsule of phalangeal joint of hand'),
(1466,'Repair of tendon of hand'),
(1467,'Other repair procedures on hand'),
(1468,'Other repair procedures on wrist'),
(1469,'Reconstruction procedures on hand'),
(1470,'Reconstruction procedures on wrist'),
(1471,'Revision procedures on hand or finger'),
(1472,'Revision procedures on wrist'),
(1473,'Procedures for mallet finger'),
(1474,'Procedures for ganglion of hand or wrist'),
(1475,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1476,'Immobilisation or traction of fracture or dislocation of pelvis or hip'),
(1477,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1478,'Osteotomy of pelvis, hip or femur'),
(1479,'Fixation of fracture of pelvis or femur'),
(1480,'Release of hip contracture'),
(1481,'Other incision of hip'),
(1482,'Biopsy of hip'),
(1483,'Ostectomy of femur or pelvis'),
(1484,'Amputation of pelvis or hip'),
(1485,'Other excision procedures on pelvis or hip'),
(1486,'Reduction of fracture of pelvis or femur'),
(1487,'Reduction of dislocation of hip'),
(1488,'Bone graft to pelvis or hip'),
(1489,'Arthroplasty of hip'),
(1490,'Transplantation or transfer of tendon or muscle of pelvis or hip'),
(1491,'Other repair procedures on pelvis or hip'),
(1492,'Revision arthroplasty of hip'),
(1493,'Procedures for slipped capital femoral epiphysis'),
(1494,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1495,'Immobilisation of fracture of fibula, patella or tibia'),
(1496,'Other application, insertion or removal procedures on knee or leg'),
(1497,'Decompression fasciotomy of calf'),
(1498,'Release of knee contracture'),
(1499,'Osteotomy of distal femur, patella, tibia or fibula'),
(1500,'Internal fixation of fracture of femoral condyle'),
(1501,'Other incision procedures on knee'),
(1502,'Biopsy of knee'),
(1503,'Arthroscopic excision of knee'),
(1504,'Excision of bone of knee or leg'),
(1505,'Other excision procedures on knee or leg'),
(1506,'Reduction of dislocation of knee or patella'),
(1507,'Closed reduction of fracture of tibial plateau'),
(1508,'Open reduction of fracture of tibial plateau'),
(1509,'Closed reduction of fracture of shaft of tibia or fibula'),
(1510,'Open reduction of fracture of shaft of tibia or fibula'),
(1511,'Removal of loose body of knee with repair'),
(1512,'Arthrodesis of knee'),
(1513,'Bone graft to tibia'),
(1514,'Lateral release of knee with repair'),
(1515,'Resection of femur and tibia with repair'),
(1516,'Transfer of tendon, ligament or bone of knee or leg'),
(1517,'Arthroscopic meniscectomy of knee with repair'),
(1518,'Arthroplasty of knee'),
(1519,'Arthroplasty of knee with bone graft to femur or tibia'),
(1520,'Other repair procedures on knee or leg'),
(1521,'Internal fixation of fracture of femur or tibia with reconstruction'),
(1522,'Reconstruction procedures on knee'),
(1523,'Revision of total arthroplasty of knee with bone graft to femur or tibia'),
(1524,'Other revision procedures on knee'),
(1525,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1526,'Immobilisation procedures on ankle or foot'),
(1527,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1528,'Osteotomy of ankle or foot'),
(1529,'Other incision procedures on ankle'),
(1530,'Other incision procedures on foot'),
(1531,'Arthroscopic excision procedures on ankle'),
(1532,'Excision of bone of foot'),
(1533,'Amputation of ankle or foot'),
(1534,'Other excision procedures on ankle or foot'),
(1535,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1536,'Closed reduction of fracture of calcaneum, talus or metatarsus'),
(1537,'Closed reduction of fracture of ankle or toe'),
(1538,'Open reduction of fracture of calcaneum, talus or metatarsus'),
(1539,'Open reduction of fracture of ankle or toe'),
(1540,'Closed reduction of dislocation of ankle or foot'),
(1541,'Open reduction of dislocation of ankle or foot'),
(1542,'Repair of tendon or ligament of ankle or foot'),
(1543,'Arthrodesis of ankle, foot or toe'),
(1544,'Other repair procedures on ankle or foot'),
(1545,'Reconstruction procedures on ankle or foot'),
(1546,'Procedures for talipes equinovarus'),
(1547,'Procedures for hallux valgus or hallux rigidus'),
(1548,'Procedures for other toe deformities'),
(1549,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1550,'Application of external fixation devices to other musculoskeletal sites'),
(1551,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1552,'Administration of agent into other musculoskeletal sites'),
(1553,'Aspiration of other musculoskeletal sites'),
(1554,'Other application, insertion or removal procedures on other musculoskeletal sites'),
(1555,'Incision procedures on joint of other musculoskeletal sites'),
(1556,'Incision procedures on bone of other musculoskeletal sites'),
(1557,'Incision procedures on tendon or tendon sheath of other musculoskeletal sites'),
(1558,'Incision of fascia of other musculoskeletal sites'),
(1559,'Incision procedures on other musculoskeletal sites'),
(1560,'Biopsy of other musculoskeletal sites'),
(1561,'Excision procedures on joint of other musculoskeletal sites'),
(1562,'En bloc resection of lesion of soft tissue affecting long bones'),
(1563,'Other excision procedures on bone of other musculoskeletal sites'),
(1564,'Excision procedures on tendon of other musculoskeletal sites'),
(1565,'Excision procedures on muscle of other musculoskeletal sites'),
(1566,'Excision procedures on other musculoskeletal sites'),
(1567,'Reduction procedures on other musculoskeletal sites'),
(1568,'Suture of other musculoskeletal sites'),
(1569,'Graft of other musculoskeletal sites'),
(1570,'En bloc resection of lesion of bone with repair of other musculoskeletal sites'),
(1571,'Other repair procedures on bone of other musculoskeletal sites'),
(1572,'Other repair procedures on tendon of other musculoskeletal sites'),
(1573,'Other repair procedures on muscle of other musculoskeletal sites'),
(1574,'Other repair procedures of other musculoskeletal sites'),
(1575,'En bloc resection of lesion of soft tissue affecting long bones with reconstruction'),
(1576,'Other reconstruction procedures on other musculoskeletal sites'),
(1577,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1578,'Limb reconstruction'),
(1579,'Other procedures for other musculoskeletal sites'),
(1580,'Single event multilevel surgery [SEMLS]'),
(1600,'Dressing of burn'),
(1601,'Dressing of other wound'),
(1602,'Administration of agent into skin and subcutaneous tissue'),
(1603,'Removal of foreign body from skin and subcutaneous tissue'),
(1604,'Other application, insertion or removal procedures on skin and subcutaneous tissue'),
(1605,'Removal of foreign body from skin and subcutaneous tissue with incision'),
(1606,'Incision and drainage of skin and subcutaneous tissue'),
(1607,'Release of skin and subcutaneous tissue'),
(1608,'Other incision procedures on skin and subcutaneous tissue'),
(1609,'Psoralens and ultraviolet A [PUVA] light therapy of skin'),
(1610,'Ultraviolet B [UVB] light therapy of skin'),
(1611,'Other phototherapy of skin'),
(1612,'Destruction of lesion of skin or cartilage'),
(1614,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1615,'Laser resurfacing of skin'),
(1616,'Abrasive therapy to skin'),
(1617,'Other destruction procedures on skin and subcutaneous tissue'),
(1618,'Biopsy of skin and subcutaneous tissue'),
(1619,'Removal of wart or molluscum contagiosum'),
(1620,'Excision of lesion of skin and subcutaneous tissue'),
(1621,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1622,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1623,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1624,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1625,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1626,'Microscopically controlled excision of lesion of skin'),
(1627,'Debridement of burn'),
(1628,'Other debridement of skin and subcutaneous tissue'),
(1629,'Removal of skin graft'),
(1630,'Excision of ulcer or sinus of skin and subcutaneous tissue'),
(1631,'Excision of fingernail'),
(1632,'Excision of toenail'),
(1633,'Excision of sweat glands'),
(1634,'Other excision procedures on skin and subcutaneous tissue'),
(1635,'Repair of wound of skin and subcutaneous tissue'),
(1636,'Repair of nail'),
(1637,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1638,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1639,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1640,'Allograft, xenograft or synthetic skin graft'),
(1641,'Split skin graft to granulating burn site'),
(1642,'Other split skin graft to granulating area'),
(1643,'Split skin graft to burn of specific sites'),
(1644,'Split skin graft to burn of other sites'),
(1645,'Other split skin graft, small'),
(1646,'Other split skin graft, extensive'),
(1647,'Split skin graft, inlay'),
(1648,'Full thickness skin graft to burn'),
(1649,'Other full thickness skin graft'),
(1650,'Dermis graft'),
(1651,'Local skin flap, single stage'),
(1652,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1653,'Direct distant skin flap'),
(1654,'Indirect distant skin flap'),
(1655,'Other repair procedures on skin and subcutaneous tissue'),
(1656,'Revision of burn scar or contracture'),
(1657,'Revision of other scar of skin'),
(1658,'Revision of skin flap'),
(1659,'Procedures for pilonidal sinus or cyst'),
(1660,'Other procedures on skin and subcutaneous tissue'),
(1661,'Insertion, removal or adjustment of tissue expander or implant'),
(1662,'Excision, eyelid'),
(1663,'Excision, ear'),
(1664,'Excision, lip'),
(1665,'Excision, tongue'),
(1666,'Liposuction and lipectomy'),
(1667,'Excision of lymphoedematous tissue'),
(1668,'Dermofat or fat graft'),
(1669,'Composite graft'),
(1670,'Fascia graft'),
(1671,'Myocutaneous flap'),
(1672,'Muscle flap'),
(1673,'Island flap'),
(1674,'Free flap'),
(1675,'Facelift, necklift and browlift'),
(1676,'Graft for symblepharon'),
(1677,'Repair of blepharoptosis'),
(1678,'Repair of ear'),
(1679,'Rhinoplasty'),
(1680,'Other repair of nose'),
(1681,'Repair of pharynx'),
(1682,'Contour reconstruction'),
(1683,'Contour restoration'),
(1684,'Reconstruction of eyelid and ear'),
(1685,'Reconstruction of lip or mouth'),
(1686,'Revision of free flap and associated procedures'),
(1687,'Revision of other plastic procedures on soft tissue'),
(1688,'Reoperation to correct previous ptosis repair of eyelid'),
(1689,'Procedures for cleft lip'),
(1690,'Procedures for cleft palate'),
(1691,'Procedures for cleft lip and anterior palate'),
(1692,'Procedures for facial nerve paralysis'),
(1693,'Excision of arteriovenous malformation [AVM]'),
(1694,'Microsurgical repair for restoration of continuity of blood vessel of distal extremity or digit'),
(1695,'Microsurgical anastomosis of blood vessel'),
(1696,'Microsurgical graft of blood vessel'),
(1697,'Fixation of transcutaneous abutment (osseointegration procedure)'),
(1698,'Implantation of titanium fixture (osseointegration procedure)'),
(1699,'Resection of mandible'),
(1700,'Resection of maxilla'),
(1701,'Resection of other facial bone'),
(1702,'Genioplasty'),
(1703,'Osteotomy or ostectomy of zygoma'),
(1704,'Osteotomy or ostectomy of zygoma with internal fixation'),
(1705,'Osteotomy or ostectomy of mandible or maxilla'),
(1706,'Osteotomy or ostectomy of mandible or maxilla with internal fixation'),
(1707,'Osteotomy or ostectomy of mandible or maxilla, procedures in combination'),
(1708,'Osteotomy or ostectomy of mandible or maxilla with internal fixation, procedures in combination'),
(1709,'Midfacial osteotomies'),
(1710,'Frontal bone advancement'),
(1711,'Correction of skull deformity'),
(1712,'Other repair of skull or facial bone'),
(1713,'Reconstruction of mandible'),
(1714,'Reconstruction of maxilla'),
(1715,'Reconstruction of zygoma'),
(1716,'Reconstruction of orbital cavity'),
(1717,'Reconstruction of other skull and facial bones'),
(1718,'Other procedures for craniostenosis'),
(1740,'Examination procedures on breast'),
(1741,'Application, insertion or removal procedures on breast'),
(1742,'Incision procedures on breast'),
(1743,'Biopsy of breast'),
(1744,'Excision of lesion of breast'),
(1745,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1746,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1747,'Subcutaneous mastectomy'),
(1748,'Simple mastectomy'),
(1749,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1750,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1751,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1752,'Other excision procedures on breast'),
(1753,'Augmentation mammoplasty'),
(1754,'Reduction mammoplasty'),
(1755,'Other repair procedures on breast'),
(1756,'Reconstruction procedures on breast'),
(1757,'Reconstruction procedures on nipple and areola'),
(1758,'Procedures involving removal or adjustment of breast prosthesis or tissue expander'),
(1759,'Other procedures on breast'),
(1780,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1784,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1786,'Superficial radiation treatment'),
(1787,'Orthovoltage radiation treatment'),
(1788,'Megavoltage radiation treatment'),
(1789,'Other megavoltage radiation treatment'),
(1790,'Brachytherapy, intracavitary, gynaecological'),
(1791,'Brachytherapy, other intracavitary sites'),
(1792,'Brachytherapy, other'),
(1793,'Removal of sealed radioactive source'),
(1794,'Brachytherapy surface applicators'),
(1795,'Administration of a therapeutic dose of unsealed radioisotope'),
(1796,'Radioactive moulds'),
(1797,'Construction and fitting of immobilisation devices or treatment accessories for radiotherapy'),
(1798,'Radiation field setting'),
(1799,'Radiation dosimetry'),
(1820,'Physiological assessment'),
(1821,'Preoperative anaesthesia assessment'),
(1822,'Assessment of personal care and other activities of daily/independent living'),
(1823,'Mental, behavioural or psychosocial assessment'),
(1824,'Other assessment, consultation, interview, examination or evaluation'),
(1825,'Electroencephalography [EEG]'),
(1826,'Neuromuscular electrodiagnosis'),
(1827,'Investigation of central nervous system evoked responses'),
(1828,'Sleep study'),
(1829,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1830,'Other diagnostic neurological tests, measures or investigations'),
(1831,'Measurement or study of visual function'),
(1832,'Perimetry'),
(1833,'Measurement of accommodation or refraction'),
(1835,'Other diagnostic ophthalmic tests, measures or investigations'),
(1836,'Auditory function tests'),
(1837,'Speech audiometry'),
(1838,'Speech audiometry involving central auditory function tests'),
(1839,'Auditory evoked potentials'),
(1840,'Electrocochleography'),
(1841,'Impedance audiometry'),
(1842,'Psychoacoustic tests'),
(1843,'Other audiometry'),
(1844,'Otoacoustic emissions evaluation'),
(1845,'Vestibular function tests'),
(1846,'Other ear, nose, mouth and throat diagnostic tests, measures or investigations'),
(1847,'Measurement of respiratory muscle strength'),
(1848,'Exercise testing to assess respiratory status'),
(1849,'Other measurement of respiratory function'),
(1850,'Vascular pressure monitoring'),
(1851,'Examination and recording of wave forms of intracranial arterial circulation'),
(1852,'Examination and recording of wave forms of peripheral vessels'),
(1853,'Ambulatory continuous electrocardiography [ECG]'),
(1854,'Patient activated ambulatory electrocardiography [ECG]'),
(1855,'Other electrocardiography [ECG]'),
(1856,'Testing of cardiac pacemaker or defibrillator'),
(1857,'Other cardiovascular diagnostic tests, measures or investigations'),
(1858,'Diagnostic tests, measures or investigations, blood and blood-forming organs'),
(1859,'Digestive system diagnostic tests, measures or investigations'),
(1860,'Cystometrography'),
(1861,'Urethral pressure profilometry'),
(1862,'Other genitourinary diagnostic tests, measures or investigations'),
(1863,'Nuclear medicine (nonimaging)'),
(1864,'Skin sensitivity allergy testing'),
(1865,'Epicutaneous patch allergy testing'),
(1866,'Other diagnostic tests, measures or investigations'),
(1867,'Counselling or education relating to personal care and other activities of daily/independent living'),
(1868,'Psychosocial counselling'),
(1869,'Other counselling or education'),
(1870,'Interventions involving assistive or adaptive device, aid or equipment'),
(1871,'Nutritional support interventions'),
(1872,'Alcohol and drug rehabilitation and detoxification'),
(1873,'Psychological/psychosocial therapies'),
(1874,'Skills training for voice, speech, fluency and communication'),
(1875,'Skills training in relation to learning, knowledge and cognition'),
(1876,'Skills training in movement'),
(1877,'Skills training in body system functions'),
(1878,'Skills training for personal care and other activities of daily/independent living'),
(1879,'Other skills training'),
(1880,'Therapies using agents, not elsewhere classified'),
(1881,'Prophylactic vaccination or inoculation against certain bacterial diseases'),
(1882,'Prophylactic vaccination or inoculation against certain viral diseases'),
(1883,'Other vaccination or inoculation'),
(1884,'Immunisation'),
(1885,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1886,'Perfusion'),
(1887,'Therapeutic interventions on eye, ear, nose, mouth and throat'),
(1888,'Hyperbaric oxygen therapy'),
(1889,'Other therapeutic interventions on respiratory system'),
(1890,'Therapeutic interventions on cardiovascular system'),
(1891,'Therapeutic collection and processing of blood/bone marrow'),
(1892,'Apheresis'),
(1893,'Administration of blood and blood products'),
(1894,'Nonincisional insertion and dilation interventions on digestive system'),
(1895,'Nonincisional irrigation, cleaning and local instillation, digestive system'),
(1896,'Nonincisional replacement or removal of therapeutic device, digestive system'),
(1897,'Nonincisional removal of foreign body or calculus from gastrointestinal tract'),
(1898,'Fluid and gas reduction of intussusception'),
(1899,'Other therapeutic interventions on digestive system'),
(1900,'Nonincisional insertion, replacement and removal of therapeutic device, genital tract'),
(1901,'Nonincisional irrigation, cleaning and local instillation, genitourinary system'),
(1902,'Nonincisional removal of therapeutic device from urinary tract'),
(1903,'Nonincisional removal of foreign body from genitourinary system'),
(1904,'Other therapeutic interventions on genitourinary system'),
(1905,'Therapeutic interventions on musculoskeletal system'),
(1906,'Implantation of hormone or living tissue'),
(1907,'Electroconvulsive therapy'),
(1908,'Other therapeutic interventions'),
(1909,'Conduction anaesthesia'),
(1910,'Cerebral anaesthesia'),
(1911,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1912,'Postprocedural analgesia'),
(1913,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1914,'Assistance interventions'),
(1915,'Other client support interventions'),
(1916,'Generalised allied health interventions'),
(1920,'Administration of pharmacotherapy'),
(1921,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1922,'Other procedures related to pharmacotherapy'),
(1940,'Ultrasound of head or neck'),
(1941,'Ultrasound of breast'),
(1942,'Ultrasound of heart'),
(1943,'Ultrasound of abdomen or pelvis'),
(1944,'Duplex ultrasound of cranial, carotid or vertebral vessels'),
(1945,'Duplex ultrasound of intrathoracic or intra-abdominal vessels'),
(1946,'Duplex ultrasound of limb'),
(1947,'Duplex ultrasound of artery or cavernosal tissue of penis'),
(1948,'Duplex ultrasound of other vessels'),
(1949,'Other ultrasound'),
(1950,'Ultrasound of other sites'),
(1951,'Tomography'),
(1952,'Computerised tomography of brain'),
(1953,'Computerised tomography of pituitary fossa (and brain)'),
(1954,'Computerised tomography of orbit (and brain)'),
(1955,'Computerised tomography of middle ear and temporal bone (and brain)'),
(1956,'Computerised tomography of facial bone and/or paranasal sinus (and brain)'),
(1957,'Computerised tomography of brain, chest and abdomen'),
(1958,'Computerised tomography of neck'),
(1959,'Computerised tomography of spine'),
(1960,'Computerised tomography of chest'),
(1961,'Computerised tomography of chest, abdomen and pelvis'),
(1962,'Computerised tomography of abdomen'),
(1963,'Computerised tomography of abdomen and pelvis'),
(1964,'Computerised tomography of pelvis'),
(1965,'Computerised tomography of limb'),
(1966,'Spiral angiography by computerised tomography'),
(1967,'Radiography of head or neck'),
(1968,'Radiography of spine'),
(1969,'Radiography of spine,  2 regions'),
(1970,'Radiography of shoulder region'),
(1971,'Radiography of upper limb'),
(1972,'Radiography of sternum or ribs'),
(1973,'Radiography of breast'),
(1974,'Other radiography of chest'),
(1975,'Radiography of gastrointestinal tract'),
(1976,'Radiography of biliary tract'),
(1977,'Radiography of abdomen or peritoneum'),
(1978,'Intravenous pyelography [IVP]'),
(1979,'Retrograde radiography of urinary system'),
(1980,'Other radiography of urinary system'),
(1981,'Radiography of pelvis'),
(1982,'Radiography of genital region'),
(1983,'Radiography of lower limb'),
(1984,'Bone studies'),
(1985,'Arthrography'),
(1986,'Radiography of whole skeleton'),
(1987,'BLOCK NOT USED IN ACHI 9th EDITION'),
(1988,'Other radiography'),
(1989,'Arteriography'),
(1990,'Other angiography'),
(1991,'Magnetic resonance angiography'),
(1992,'Digital subtraction angiography of head or neck'),
(1993,'Digital subtraction angiography of thorax'),
(1994,'Digital subtraction angiography of abdomen'),
(1995,'Digital subtraction angiography of upper limb'),
(1996,'Digital subtraction angiography of lower limb'),
(1997,'Digital subtraction angiography of aorta and lower limb'),
(1998,'Other digital subtraction angiography'),
(1999,'Fluoroscopy'),
(2000,'Nuclear medicine imaging brain study'),
(2001,'Nuclear medicine imaging tear duct or salivary study'),
(2002,'Gated cardiac blood pool study'),
(2003,'Myocardial perfusion study'),
(2004,'Myocardial perfusion study with single photon emission computerised tomography [SPECT]'),
(2005,'Other circulatory system nuclear medicine imaging study'),
(2006,'Lung perfusion or ventilation study'),
(2007,'Nuclear medicine imaging study of gastrointestinal tract'),
(2008,'Renal nuclear medicine imaging study'),
(2009,'Localised bone nuclear medicine imaging study'),
(2010,'Localised joint nuclear imaging study'),
(2011,'Whole body bone nuclear medicine imaging study'),
(2012,'Whole body nuclear medicine imaging study'),
(2013,'Localised nuclear medicine imaging study'),
(2014,'Other nuclear medicine imaging study'),
(2015,'Magnetic resonance imaging'),
(2016,'Other imaging services'),
(2050,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2051,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2052,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2053,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2054,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2055,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2056,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2057,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2058,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2059,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2060,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2061,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2062,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2063,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2064,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2065,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2066,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2067,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2068,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2069,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2070,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2071,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2072,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2073,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2074,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2075,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2076,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2077,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2078,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2079,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2080,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2081,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2082,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2083,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2084,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2085,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2086,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2087,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2088,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2089,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2090,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2091,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2092,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2093,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2094,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2095,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2096,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2097,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2098,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2099,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2100,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2101,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2102,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2103,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2104,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2105,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2106,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2107,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2108,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2109,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2110,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2111,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2112,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2113,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2114,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2115,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2116,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2117,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2118,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2119,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2120,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2121,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2122,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2123,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2124,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2125,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2126,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2127,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2128,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2129,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2130,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2131,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2132,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2133,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2134,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2135,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2136,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2137,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2138,'BLOCK NOT USED IN ACHI 9th EDITION'),
(2139,'BLOCK NOT USED IN ACHI 9th EDITION');
