alter table hospital add suburb varchar(100);
update hospital set suburb = 'Hamlyn Heights' where hospital_id='GraceMcKel';
update hospital set suburb = 'Ouyen' where hospital_id='MalleeTrac';
update hospital set suburb = 'Forest Hill' where hospital_id='PeterJames';
update hospital set suburb = 'Kew' where hospital_id='StGeorgesA';
update hospital set suburb = 'Warrnambool' where hospital_id='Warrnamboo';
update hospital set suburb = 'Yarram' where hospital_id='Yarrum';
update hospital set suburb = 'Caulfield South' where hospital_id='Bethlehem';
update hospital set suburb = 'Cobram' where hospital_id='Cobram';
update hospital set suburb = 'Lilydale' where hospital_id='YarraRange';
update hospital set suburb = 'Kew' where hospital_id='CaritasChr';
update hospital set suburb = 'Footscray' where hospital_id='OrygenYout';
update hospital set suburb = 'Bacchus Marsh' where hospital_id='Djerriwarr';
update hospital set suburb = 'Heidelberg' where hospital_id='AustinHeal';
update hospital set suburb = 'Colac' where hospital_id='ColacAreaH';
update hospital set suburb = 'Cranbourne' where hospital_id='Cranbourne';
update hospital set suburb = 'Hepburn' where hospital_id='Creswick';
update hospital set suburb = 'Echuca' where hospital_id='EchucaRegi';
update hospital set suburb = 'Hamilton' where hospital_id='HamiltonBa';
update hospital set suburb = 'Melton' where hospital_id='MeltonHeal';
update hospital set suburb = 'Clayton' where hospital_id='MonashMedi';
update hospital set suburb = 'Footscray' where hospital_id='WesternHos';
update hospital set suburb = 'Sale' where hospital_id='CentralGip';
update hospital set suburb = 'Horsham' where hospital_id='WimmeraBas';
update hospital set suburb = 'Warragul' where hospital_id='WestGippsl';
update hospital set suburb = 'Wonthaggi' where hospital_id='BassCoastR';
update hospital set suburb = 'Swan Hill' where hospital_id='SwanHillDi';
update hospital set suburb = 'Melbourne' where hospital_id='RoyalDenta';
update hospital set suburb = 'Rosebud' where hospital_id='RosebudHos';
update hospital set suburb = 'Broadmeadows' where hospital_id='Broadmeado';
update hospital set suburb = 'Caulfield' where hospital_id='Caulfield';
update hospital set suburb = 'Maryborough' where hospital_id='Maryboroug';
update hospital set suburb = 'Portland' where hospital_id='PortlandDi';
update hospital set suburb = 'Sunbury' where hospital_id='SunburyDay';
update hospital set suburb = 'Ararat' where hospital_id='Ararat';
update hospital set suburb = 'Casterton' where hospital_id='Casterton';
update hospital set suburb = 'Numurkah' where hospital_id='Numurkah';
update hospital set suburb = 'Bendigo' where hospital_id='BendigoHos';
update hospital set suburb = 'Warracknabeal' where hospital_id='Warracknab';
update hospital set suburb = 'Bright' where hospital_id='Bright';
update hospital set suburb = 'Lorne' where hospital_id='Lorne';
update hospital set suburb = 'Myrtleford' where hospital_id='Myrtleford';
update hospital set suburb = 'Rochester' where hospital_id='Rochester';
update hospital set suburb = 'Donald' where hospital_id='Donald';
update hospital set suburb = 'Clayton' where hospital_id='Moorabbin';
update hospital set suburb = 'Wangaratta' where hospital_id='NortheastH';
update hospital set suburb = 'Nathalia' where hospital_id='Nathalia';
update hospital set suburb = 'Wycheproof' where hospital_id='Wycheproof';
update hospital set suburb = 'Melbourne' where hospital_id='PeterMacCa';
update hospital set suburb = 'Noble Park' where hospital_id='QECNoblePa';
update hospital set suburb = 'Sandringham' where hospital_id='Sandringha';
update hospital set suburb = 'Yarrawonga' where hospital_id='Yarrawonga';
update hospital set suburb = 'Heywood' where hospital_id='Heywood';
update hospital set suburb = 'Jeparit' where hospital_id='Jeparit';
update hospital set suburb = 'Hopetoun' where hospital_id='Hopetoun';
update hospital set suburb = 'Tallangatta' where hospital_id='Tallangatt';
update hospital set suburb = 'Hesse' where hospital_id='Hesse';
update hospital set suburb = 'Maldon' where hospital_id='Maldon';
update hospital set suburb = 'Coleraine' where hospital_id='Coleraine';
update hospital set suburb = 'Willaura' where hospital_id='Willaura';
update hospital set suburb = 'Skipton' where hospital_id='Skipton';
update hospital set suburb = 'Penshurst' where hospital_id='Penshurst';
update hospital set suburb = 'Dunolly' where hospital_id='Dunolly';
update hospital set suburb = 'Castlemaine' where hospital_id='Castlemain';
update hospital set suburb = 'Benalla' where hospital_id='Benalla';
update hospital set suburb = 'Kyabram' where hospital_id='Kyabram';
update hospital set suburb = 'Stawell' where hospital_id='Stawell';
update hospital set suburb = 'Craigieburn' where hospital_id='Craigiebur';
update hospital set suburb = 'Seymour' where hospital_id='Seymour';
update hospital set suburb = 'Leongatha' where hospital_id='Leongatha';
update hospital set suburb = 'Boort' where hospital_id='BoortDistr';
update hospital set suburb = 'Edenhope' where hospital_id='Edenhopean';
update hospital set suburb = 'Kingston' where hospital_id='KingstonCe';
update hospital set suburb = 'Epping' where hospital_id='NorthernHo';
update hospital set suburb = 'Omeo' where hospital_id='OmeoDistri';
update hospital set suburb = 'Colac' where hospital_id='OtwayHealt';
update hospital set suburb = 'Melbourne' where hospital_id='RoyalMelbo';
update hospital set suburb = 'Melbourne' where hospital_id='RoyalChild';
update hospital set suburb = 'Kew' where hospital_id='RoyalTalbo';
update hospital set suburb = 'Melbourne' where hospital_id='RoyalVicto';
update hospital set suburb = 'Melbourne' where hospital_id='RoyalWomen';
update hospital set suburb = 'Melbourne' where hospital_id='StVincents';
update hospital set suburb = 'Geelong' where hospital_id='University';
update hospital set suburb = 'Werribee' where hospital_id='WerribeeMe';
update hospital set suburb = 'Royal Park' where hospital_id='RoyalPark';
update hospital set suburb = 'Kyneton' where hospital_id='Kyneton';
update hospital set suburb = 'Kerang' where hospital_id='Kerang';
update hospital set suburb = 'Shepparton' where hospital_id='Shepparton';
update hospital set suburb = 'Wodonga' where hospital_id='WodongaHos';
update hospital set suburb = 'Kilmore' where hospital_id='Kilmore';
update hospital set suburb = 'Nhill' where hospital_id='Nhill';
update hospital set suburb = 'Mansfield' where hospital_id='Mansfield';
update hospital set suburb = 'Camperdown' where hospital_id='SouthWesth';
update hospital set suburb = 'Cohuna' where hospital_id='Cohuna';
update hospital set suburb = 'Robinvale' where hospital_id='Robinvale';
update hospital set suburb = 'Alexandra' where hospital_id='AlexandraH';
update hospital set suburb = 'Terang' where hospital_id='Terang';
update hospital set suburb = 'Ballarat' where hospital_id='BallaratQE';
update hospital set suburb = 'Bundoora' where hospital_id='BECC';
update hospital set suburb = 'Orbost' where hospital_id='OrbostRegi';
update hospital set suburb = 'Prahran' where hospital_id='AlfredHeal';
update hospital set suburb = 'Korumburra' where hospital_id='Korumburra';
update hospital set suburb = 'Mornington' where hospital_id='TheMorning';
update hospital set suburb = 'Wantirna' where hospital_id='WantirnaHe';
update hospital set suburb = 'Ringwood East' where hospital_id='MaroondahH';
update hospital set suburb = 'Port Fairy' where hospital_id='Moyne';
update hospital set suburb = 'Koo Wee Rup' where hospital_id='Kooweerup';
update hospital set suburb = 'Wodonga' where hospital_id='AlburyWodo';
update hospital set suburb = 'Traralgon' where hospital_id='LatrobeReg';
update hospital set suburb = 'Corryong' where hospital_id='Corryong';
update hospital set suburb = 'Mount Beauty' where hospital_id='MountBeaut';
update hospital set suburb = 'St Arnaud' where hospital_id='StArnaud';
update hospital set suburb = 'Beechworth' where hospital_id='Beechworth';
update hospital set suburb = 'Birchip' where hospital_id='Birchip';
update hospital set suburb = 'Heathcote' where hospital_id='HeathcoteH';
update hospital set suburb = 'Yea' where hospital_id='Yea';
update hospital set suburb = 'Maffra' where hospital_id='Maffra';
update hospital set suburb = 'Kaniva' where hospital_id='Kaniva';
update hospital set suburb = 'Bairnsdale' where hospital_id='Bairnsdale';
update hospital set suburb = 'Inglewood' where hospital_id='Inglewood';
update hospital set suburb = 'Rainbow' where hospital_id='Rainbow';
update hospital set suburb = 'Beaufort' where hospital_id='Beaufort';
update hospital set suburb = 'Tatura' where hospital_id='Tatura';
update hospital set suburb = 'Waranga' where hospital_id='Waranga';
update hospital set suburb = 'Dandenong' where hospital_id='DandenongH';
update hospital set suburb = 'Sunshine' where hospital_id='SunshineHo';
update hospital set suburb = 'Box Hill' where hospital_id='BoxHillHos';
update hospital set suburb = 'Frankston' where hospital_id='FrankstonH';
update hospital set suburb = 'Casey' where hospital_id='CaseyHospi';
update hospital set suburb = 'Ballarat' where hospital_id='BallaratHo';
update hospital set suburb = 'Timboon' where hospital_id='Timboon';
update hospital set suburb = 'Williamstown' where hospital_id='Williamsto';
update hospital set suburb = 'Healesville' where hospital_id='Healesvill';
update hospital set suburb = 'Upper Ferntree Gully' where hospital_id='AnglissHos';
update hospital set suburb = 'Bendigo' where hospital_id='AnneCaudle';
update hospital set suburb = 'Heidelberg' where hospital_id='Heidelberg';
update hospital set suburb = 'Daylesford' where hospital_id='HepburnHea';
update hospital set suburb = 'Heidelberg' where hospital_id='MercyWomen';
update hospital set suburb = 'Mildura' where hospital_id='MilduraBas';
update hospital set suburb = 'Sea Lake' where hospital_id='SeaLakeDis';
update hospital set suburb = 'Canterbury' where hospital_id='OConnellCe';
update hospital set suburb = 'Rupanyup' where hospital_id='Dunmunkle';
update hospital set suburb = 'Frankston' where hospital_id='GolfLinksR';
update hospital set suburb = 'Footscray' where hospital_id='TweddleCen';

